### ISSUE TITLE
Compile and Intall problem

### ISSUE THREAD

**Issue by wliebtzy** [tudelft3d/3D_Urban_Mesh_Annotator#2]
Hi maintainer,
thanks for your shared annotator. But during the compiling and installation, cmake can't find the GMP path. And I try to download gmp and compile it, but a new problem occurred. Cmake needs the MPFR path. But in windows system, I can't use the MPFR to compile. Do you have some advice for that? Or could you please write a more detailed tutorial?

**Comment by WeixiaoGao** [comment]
Hi, thank you for your interest in our project. Please refer to [CGAL GMP and MPFR](https://geometrica.saclay.inria.fr/team/Marc.Glisse/tmp/kda/Manual/installation.html#:~:text=C%3A%5Cboost%5Cboost_1_41_0.-,8.3%20GMP%20and%20MPFR,-The%20components%20libCGAL) for more details, and they provide a precompiled version of these two libraries.

**Comment by wliebtzy** [comment]
@WeixiaoGao  Thank you for your suggestion. I have tried to solve the problem with GMP and MPFR. After that, I restart the Cmake, and the result is shown as following:
![image](https://user-images.githubusercontent.com/33228694/160609346-2e1cab76-b7f2-4ca7-b0d3-4b8cdb7447e9.png)

And the ErrorLog denotes:
![image](https://user-images.githubusercontent.com/33228694/160609777-afc8f35a-36a9-4914-90ad-c19f9e942cb0.png)

How can I modify it?

Best Regards!

**Comment by WeixiaoGao** [comment]
It seems something goes wrong with your Eigen library, please check that you include the correct path to Eigen.
