### ISSUE TITLE
Visualization of Segment Results in SUMS Software

### ISSUE THREAD

**Issue by Berlin000000** [tudelft3d/3D_Urban_Mesh_Annotator#3]
Hello Dr. Gao, when processing data using your other software "SUMS: Semantic Urban Mesh Segmentation," I obtained segment results and final classification results. However, I was only successful in visualizing the classification results using the Annotator software. The segment results caused the software to exit automatically after loading for a while. I'm wondering if the current Annotator software supports visualizing segment results. If not, do you have any suggestions for visualizing segment results?

**Comment by WeixiaoGao** [comment]
You can use [Mapple](https://github.com/LiangliangNan/Easy3D/releases) to visualize the segmentation results.
